### ISSUE TITLE
Aspektverhältnisse berücksichtigen

### ISSUE THREAD

**Issue by tbrede** [MBrede/bean_counter#26]
Als Kriterium für eine Korngrenze, aber deaktivierbar, oder sogar verstellbar, da es auch zu langen Körnern kommen kann.

Im NOrmalfall: Ist ein Cluster sehr viel länger in eine Richtung als in eine Andere, ist er vermutlich eine Korngrenze

**Comment by MBrede** [comment]
In Settings hinzugefügt
